bin/ipr: Removed '*' (star) to message helpers

diff --git a/bin/ipr b/bin/ipr
--- a/bin/ipr
+++ b/bin/ipr
@@ -41,15 +41,15 @@ exit $?
 
 pr_info()
 {
-	echo -e "\e[1;34m* INFO:\e[0;35m${0##*/}\e[0m: ${@}"
+	echo -e "\e[1;34mINFO:\e[0;35m${0##*/}\e[0m: ${@}"
 }
 pr_error()
 {
-	echo -e "\e[1;31m* ERROR:\e[0;36m${0##*/}\e[0m: ${@}" >&2
+	echo -e "\e[1;31mERROR:\e[0;36m${0##*/}\e[0m: ${@}" >&2
 }
 pr_warn()
 {
-	echo -e "\e[1;33m* WARN:\e[0;32m${0##*/}\e[0m: ${@}" >&2
+	echo -e "\e[1;33mWARN:\e[0;32m${0##*/}\e[0m: ${@}" >&2
 }
 die()
 {
