xtr: update: 2;0 version bump

diff --git a/scr/xtr b/scr/xtr
--- a/scr/xtr
+++ b/scr/xtr
@@ -1,27 +1,30 @@
 #!/bin/sh
-# $Id: ~/scr/xtr,v 2014/07/31 14:00:26 -tclover Exp $
-
+#
+# $Id: xtr,v 2.0 2014/08/31 14:00:26 -tclover        Exp $
+# $License: MIT (or 2-clause/new/simplified BSD) Exp $
+#
 # @SCRIPT: xtr
-# @DESCRIPTION: eXTRact archives or tarball archives
-# @USAGE: [-c<comp_opt>] [-g<gpg_opt>] <file> <file> <...>
+# @DESCRIPTION: simple and short script to eXTRact archives or tarball archives
+# @USAGE: [-c|--comp <comp-opt>] [-g|--gpg <gpg-opt>] <file> <file> <...>
 
-usage () {
-   echo "usage: xtr -c<comp_opt> <file> <file> <...>"
+usage() {
+   echo "usage:  xtr [option] <file> <file> <...>"
+   echo "option: [-c|--comp <comp-opt>] [-g|--gpg <gpg-opt>]"
+   echo "help:   [-h|--help]"
    exit
 }
 
 [ $# == 0 ] && usage
 
-for arg in "$@"; do
-	case "${arg##*.}" in
-		*.gpg) gpg=gpg;;
-		-c*) c_opt="${arg#*-c}"
-		     continue;;
-		-g*) g_opt="${arg#*-g}"
-		     continue;;
-		-u|--usage) usage;;
-	esac
+while [ $# -ge 1 ]; do
 	case "$arg" in
+		*.gpg) gpg=gpg;;
+		-c|--comp) c_opt="$2"
+		     shift 2;;
+		-g|--gpg) g_opt="$2"
+		     shift 2;;
+		-h|--help) usage;;
+
 		*.tbz*2*|*.tar.bz*2*) cmp="tar -xvjf";;
 		*.txz*|*.tar.xz*) cmp="tar -xvJf";;
 		*.tgz*|*.tar.gz*) cmp="tar -xvzf";;
@@ -38,16 +41,22 @@ for arg in "$@"; do
 		*.gz*) cmp=gunzip;;
 		*.7z*) cmp="7z x";;
 		*.Z*) cmp=uncompress;;
-		*) echo "xtr: unrecongnized $arg argument"
-		   exit 1;;
+		*) echo "xtr: unrecongnized $arg argument/option" >&2
+		   usage;;
 	esac
+
 	if [ -n "$gpg" ]; then
 		$gpg -d "$arg" $g_opt | $cmp $opt $c_opt -
+		ret=$?
 	else
 		$cmp $c_opt "$arg"
+		ret=$?
 	fi
+
+	[ $ret != 0 ] && echo "xtr: failed to extract $1" >&2
+	shift
 done
 
-unset cmp gpg arg c_opt g_opt
+unset cmp gpg arg c_opt g_opt ret
 
-# vim:fenc=utf-8:ft=zsh:ci:pi:sts=0:sw=2:ts=2:
+# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
