.scripts/fhp: (m) edit

diff --git a/.scripts/fhp b/.scripts/fhp
--- a/.scripts/fhp
+++ b/.scripts/fhp
@@ -1,16 +1,16 @@
 #!/bin/sh
-# $Id: ~/.scripts/fhp,v 1.0 2012/09/28 11:29:44 -tclover Exp $
+# $Id: ~/.scripts/fhp,v 1.0 2012/10/20 08:41:58 -tclover Exp $
 # a script to put firefox profile to tmpfs, the following line should be put in 
 # ~/.*shrc or ~/.*profile: `export FHP=$(ls -d ~/.mozilla/firefox/*.default)'
 # and something like... in a crontab job: */30 * * * * $USER ~/.scripts/fhp.bash
 die() {  echo "* $@"; exit 1; }
 [[ -z $FHP ]] && die "FHP profile env string is empty."
-if [[ -z $(sudo mount -t tmpfs | grep -F $FHP) ]]; then
-	sudo mount fhp-$UID "$FHP" -t tmpfs -o nodev,noexec,uid=$UID,gid=$GID,size=128m || \
-		die "failed to mount fhp-$UID tmpfs"; fi
+[[ -z $(sudo mount -t tmpfs | grep -F $FHP) ]] &&
+	sudo mount fhp "$FHP" -t tmpfs -o nodev,noexec,uid=$UID,gid=$GID,size=128m ||
+	die "failed to mount fhp"
 cd "${FHP%/*}"
 if [[ -f "$FHP"/.unpacked ]]; then
-	tar --exclude $FHP/.unpacked -czpf ${FHP##*/}.tmp.tgz ${FHP##*/}/ || \
+	tar --exclude $FHP/.unpacked -czpf ${FHP##*/}.tmp.tgz ${FHP##*/}/ ||
 		die "failed to pack the profie."
 	mv ${FHP##*/}.tgz ${FHP##*/}.old.tgz || die "failed to override .old profile."
 	mv ${FHP##*/}.tmp.tgz ${FHP##*/}.tgz || die "failed to move the profile."
